import { Metadata } from "next";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "GameGen Disclaimer - Important legal information.",
};

export default function DisclaimerPage() {
  return (
    <div className="relative min-h-screen">
      <Navbar />
      <main className="pt-24 pb-20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h1 className="text-4xl sm:text-5xl font-bold mb-6">Disclaimer</h1>
          </div>

          <div className="prose prose-neutral dark:prose-invert max-w-none">
            <h2>General Disclaimer</h2>
            <p>
              The information provided on GameGen is for general informational purposes only. 
              While we strive to keep the information accurate and up to date, we make no representations 
              or warranties of any kind about the completeness, accuracy, reliability, or availability of the service.
            </p>

            <h2>Generated Content</h2>
            <p>
              All names, text styles, and symbols generated by our tool are created algorithmically. 
              We do not guarantee that generated names will be available on any specific platform or game. 
              Users are responsible for checking name availability on their target platforms.
            </p>

            <h2>Third-Party Platforms</h2>
            <p>
              GameGen is not affiliated with, endorsed by, or sponsored by any gaming platform, social media site, 
              or game developer. All trademarks and registered trademarks are the property of their respective owners.
            </p>

            <h2>AdSense and Advertising</h2>
            <p>
              This website uses Google AdSense to display advertisements. Google may use cookies to serve ads 
              based on your prior visits to this and other websites. You can opt out of personalized advertising 
              by visiting Google Ads Settings.
            </p>

            <h2>External Links</h2>
            <p>
              Our website may contain links to external sites. We are not responsible for the content or 
              privacy practices of these external websites.
            </p>

            <h2>Changes</h2>
            <p>
              We reserve the right to make changes to this disclaimer at any time without prior notice.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
